version: '3.8'

services:
  comfyui:
    build: .
    container_name: comfyui-pod
    ports:
      - "8188:8188"
      - "8888:8888"
      - "8090:8090"
      - "8000:8000"
    volumes:
      - ./workspace:/workspace
      - ./models:/workspace/models
      - ./outputs:/workspace/outputs
      - ./inputs:/workspace/inputs
    environment:
      - ENABLE_JUPYTER=true
      - ENABLE_FILEBROWSER=true
      - ENABLE_API=true
      - INSTALL_FACEID_MODELS=true
      - CIVITAI_TOKEN=${CIVITAI_TOKEN:-}
      - HF_TOKEN=${HF_TOKEN:-}
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: comfyui-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - comfyui
    restart: unless-stopped
    profiles:
      - production

