version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
      resource_class: large
    steps:
      - checkout

      - run:
          name: Login to Docker Hub
          command: |
            if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
              echo "Missing DOCKERHUB_USERNAME/DOCKERHUB_TOKEN in CircleCI project settings" >&2
              exit 1
            fi
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - run:
          name: Enable buildx
          command: |
            docker run --privileged --rm tonistiigi/binfmt --install all || true
            docker buildx create --name builder --use || docker buildx use builder

      - run:
          name: Build and push (with registry cache)
          command: |
            set -eux
            IMAGE="$DOCKERHUB_USERNAME/comfyui-runpod:latest"
            CACHE_REF="$DOCKERHUB_USERNAME/comfyui-runpod:buildcache"
            docker buildx build \
              --push \
              --progress plain \
              --tag "$IMAGE" \
              --cache-from=type=registry,ref="$CACHE_REF" \
              --cache-to=type=registry,mode=max,ref="$CACHE_REF" \
              .

workflows:
  build-and-push:
    jobs:
      - build
